spring:
  datasource:
    url: jdbc:h2:mem:memoryNOC
    driverClassName: org.h2.Driver
    username: sa
    password: "!moreComplexPasswordThanNeededForTests0"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
management:
  endpoints:
    enabled-by-default: true