-- INCARNATION EPOCH
INSERT INTO T_INCARNATION_EPOCH (id, cost, name, era)
VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 0, 'Fall of Atlantis', 'LOST_ERA');
INSERT INTO T_INCARNATION_EPOCH (id, cost, name, era)
VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 2, 'The Deluge', 'ELEMENTARY_WARS');

-- LOCATIONS
INSERT INTO ET_EPOCH_LOCATION (id, location)
VALUES (1, 'Atlantis');

-- DEGREES


-- DEGREE VALUES


-- SIMULACRUM