package org.rorschachdb.nephilim.online.creator.back.model;

import lombok.*;

import javax.persistence.*;

/**
 * TODO copy confluence description
 */
@Entity
@Table(name = "T_INCARNATION_EPOCH")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class IncarnationEpoch {

    /**
     * Technical identifier (autogenerated)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    /**
     * TODO copy confluence description
     */
    @Column(nullable = false, unique = true, updatable = true)
    private String name;

}
