package org.rorschachdb.nephilim.online.creator.back.model;

import lombok.*;

import javax.persistence.*;

/**
 * TODO copy confluence description
 */
@Entity
@Table(name = "T_INCARNATION_EPOCH")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class IncarnationEpoch {

    /**
     * Technical identifier (autogenerated)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    /**
     * IncarnationEpoch's designation - conceptual key
     */
    @Column(nullable = false, unique = true, updatable = true)
    private String name;

    /**
     * IncarnationEpoch's summary : context, events, people
     */
    @Column(updatable = true, length = 5000)
    private String description;

    /**
     * Price in incarnation points for a character to acquire an IncarnationEpoch
     * TODO: add validation (from 0 to 2)
     */
    @Column(nullable = false, updatable = true)
    private int cost;

//    /**
//     * Array of geographical loci where the IncarnationEpoch takes place
//     */
//    private String[] locations = {};

}
