package org.rorschachdb.nephilim.online.creator.back.model.entities;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.rorschachdb.nephilim.online.creator.back.model.enums.DegreeTypeEnum;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

/**
 * A character's skill
 */
@Entity
@Table(name = "T_DEGREE")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Degree {

    /**
     * Technical identifier (autogenerated)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    /**
     * Degree's designation - conceptual key
     */
    @NotBlank
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * Degree's definition
     */
    @Column(length = 3000)
    private String description;

    /**
     * Category of degrees which the Degree is part of
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DegreeTypeEnum type;
}
