
/*
 * nephilim.online.creator.back
 *
 * Copyright (c) 2022 by rorshach-corp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.rorschachdb.nephilim.online.creator.back.model.entities;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.rorschachdb.nephilim.online.creator.back.model.enums.DegreeTypeEnum;

import java.io.Serializable;

/**
 * A character's skill
 */
@Entity
@Table(name = "T_DEGREE")
@Inheritance
@DiscriminatorColumn(name = "type")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Degree implements Serializable {
    /**
     * Technical identifier (autogenerated)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_degree")
    @SequenceGenerator(name = "seq_degree", allocationSize = 1)
    private Long id;


    /**
     * Degree's designation - conceptual key
     */
    @NotBlank
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * Degree's definition
     */
    @Column(length = 3000)
    private String description;

    /**
     * Category of degrees which the Degree is part of
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, insertable = false, updatable = false)
    private DegreeTypeEnum type;
}
